#!/bin/bash

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VARS_FILE="$SCRIPT_DIR/vars.sh"

echo "=================================================="
echo "  AWS Vocareum Credentials Reminder"
echo "=================================================="
echo ""

# Create vars.sh, or clear it if it already exists, then populate it
> "$VARS_FILE"
echo "#!/usr/bin/env bash" >> "$VARS_FILE"
echo "PROFILE=ACS730" >> "$VARS_FILE"
chmod +x "$VARS_FILE"

echo "vars.sh file created to store profile name, region"
echo "and other vars that will be used by the scripts on"
echo "later phases"
echo ""

echo "--------------------------------------------------"
echo ""
echo "1. Verify that the AWS CLI is installed by running:"
echo ""
echo "     which aws"
echo ""
echo "2. Go to your Vocareum lab environment"
echo "3. Click the 'AWS CLI' / 'Account Details' button"
echo "4. Copy the credentials block shown there"
echo "5. Paste it into ~/.aws/credentials, replacing"
echo "   the existing [ACS730] section"
echo ""
echo "   The credentials file is located at:"
echo "     ~/.aws/credentials"
echo ""
echo "   To find/open it, run:"
echo "     ls -la ~/.aws/"
echo "     nano ~/.aws/credentials"
echo ""
echo "   Your credentials file should be structured as follows:"
echo ""
echo "     [default]"
echo "     aws_access_key_id=<KEY_ID_HERE>"
echo "     aws_secret_access_key=<KEY_HERE>"
echo ""
echo "     [ACS730]"
echo "     aws_access_key_id=<KEY_ID_HERE>"
echo "     aws_secret_access_key=<KEY_HERE>"
echo "     aws_session_token=<TOKEN_HERE>"
echo ""
echo "   (If ~/.aws/ or the file doesn't exist yet, create it with:"
echo "     mkdir -p ~/.aws && touch ~/.aws/credentials)"
echo ""
echo "6. Create or modify the config file located in ~/.aws/config"
echo ""
echo "     nano ~/.aws/config"
echo ""
echo "   Your config file should be structured as follows:"
echo ""
echo "     [default]"
echo "     region = <REGION_HERE>"
echo "     output = <OUTPUT_HERE>"
echo ""
echo "     [profile ACS730]"
echo "     region = <REGION_HERE>"
echo "     output = <OUTPUT_HERE>"
echo ""
echo "7. Verify with:"
echo "     aws sts get-caller-identity --profile ACS730"
echo ""
echo "Note: the session token expires every few hours —"
echo "repeat this whenever your AWS calls start failing."
echo "=================================================="